#############################################################################
# Makefile for building: musicbeat
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  ..\musicbeat\musicbeat.pro
# Template: app
#############################################################################

MAKEFILE      = Makefile.Release

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN
CFLAGS        = -fno-keep-inline-dllexport -O2 -Wall -Wextra -Wextra $(DEFINES)
CXXFLAGS      = -fno-keep-inline-dllexport -O2 -std=gnu++11 -Wall -Wextra -Wextra -fexceptions -mthreads $(DEFINES)
INCPATH       = -I..\musicbeat -I. -I..\..\qt\5.14.2\mingw73_32\include -I..\..\qt\5.14.2\mingw73_32\include\QtMultimedia -I..\..\qt\5.14.2\mingw73_32\include\QtWidgets -I..\..\qt\5.14.2\mingw73_32\include\QtGui -I..\..\qt\5.14.2\mingw73_32\include\QtANGLE -I..\..\qt\5.14.2\mingw73_32\include\QtNetwork -I..\..\qt\5.14.2\mingw73_32\include\QtCore -Irelease -I. -I..\..\qt\5.14.2\mingw73_32\mkspecs\win32-g++ 
LINKER      =        g++
LFLAGS        =        -Wl,-s -Wl,-subsystem,windows -mthreads
LIBS        =        D:\qt\5.14.2\mingw73_32\lib\libQt5Multimedia.a D:\qt\5.14.2\mingw73_32\lib\libQt5Widgets.a D:\qt\5.14.2\mingw73_32\lib\libQt5Gui.a D:\qt\5.14.2\mingw73_32\lib\libQt5Network.a D:\qt\5.14.2\mingw73_32\lib\libQt5Core.a  -lmingw32 D:\qt\5.14.2\mingw73_32\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.7.25-win32\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 
QMAKE         = D:\qt\5.14.2\mingw73_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\qt\5.14.2\mingw73_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\qt\5.14.2\mingw73_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move

####### Output directory

OBJECTS_DIR   = release

####### Files

SOURCES       = ..\musicbeat\choosemusic.cpp \
		..\musicbeat\endgame.cpp \
		..\musicbeat\gamecenter.cpp \
		..\musicbeat\gamehelp.cpp \
		..\musicbeat\main.cpp \
		..\musicbeat\mainwindow.cpp \
		..\musicbeat\notelist.cpp \
		..\musicbeat\notes.cpp \
		..\musicbeat\topscore.cpp \
		..\musicbeat\updatagame.cpp release\qrc_res.cpp \
		release\moc_choosemusic.cpp \
		release\moc_endgame.cpp \
		release\moc_gamecenter.cpp \
		release\moc_gamehelp.cpp \
		release\moc_mainwindow.cpp \
		release\moc_topscore.cpp \
		release\moc_updatagame.cpp
OBJECTS       = release/choosemusic.o \
		release/endgame.o \
		release/gamecenter.o \
		release/gamehelp.o \
		release/main.o \
		release/mainwindow.o \
		release/notelist.o \
		release/notes.o \
		release/topscore.o \
		release/updatagame.o \
		release/qrc_res.o \
		release/moc_choosemusic.o \
		release/moc_endgame.o \
		release/moc_gamecenter.o \
		release/moc_gamehelp.o \
		release/moc_mainwindow.o \
		release/